project:
  type: website
  render: 
  - model.qmd

website:
  title: "palmer"
  navbar:
    left:
      - href: model.qmd
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



